# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dbcb3912a5a933990612998ad4d4e9da2f75dbf1a3741986cfe147e37ca6d42c37b00c86799b7808dd367255a58e678061d09b989091c1f958f4fd72cf71017

test:
  secret_key_base: c88e636c2667ab36746829ea517eebc8312089b3a101dd55679a487d8e8df6fe48f92254b4e7545b298a7778787e990c748cccba842d1eb5c50c4b731e360e72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
